
# Project information
site_url: https://ros-fe.github.io/fe-ros-docs/
site_author: Timotej Gašpar
site_description: >-
  FE ROS workshop documentation page.
# Repository
repo_name: ROS-FE/fe-ros-docs
repo_url: https://github.com/ROS-FE/fe-ros-docs

site_name: FE ROS
nav:
    - Home: 'index.md'
    - About: 'about/index.md'
    - Introduction to ROS: 'introduction/index.md'
    - Spatial transformations and trajectory planning:
      - 'tf_moveit/index.md'
      - Transformations: 'tf_moveit/tf.md'
      - Describing frame relations with URDF: 'tf_moveit/urdf.md'
      - Assignment: 'tf_moveit/assignment.md'
    - Visualization & Simulation: 'simulation/index.md'
    - Practical work with robots: 'practical/index.md'
    - Sponsors: 'sponsors/index.md'
    - Additional knowledge: 'additional/index.md'
theme:
  name: material
  palette:
    - scheme: default
      toggle:
        icon: material/lightbulb-outline
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/lightbulb
        name: Switch to light mode
  features:
      - toc.integrate
  favicon: assets/logo.png
  # logo: https://raw.githubusercontent.com/ros-infrastructure/artwork/master/orgunits/ros.svg

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

extra_javascript:
  - assets/javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
